version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      NODE_ENV: development
      WORDPRESS_DB_HOST: maria
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    links:
      - maria
    volumes:
      - ./..:/var/www/html:rw

  maria:
    image: mariadb
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: 'pass123'
    volumes:
      - maria:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 6080:8080

volumes:
  wordpress:
  maria:
  adminer:
