version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    links:
      - database
    volumes:
      - ./..:/var/www/html:rw

  database:
    image: mariadb
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: 'pass123'
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 6080:8080

volumes:
  wordpress:
  database:
  adminer: